# config/app.yml for rails-settings-cached
defaults: &defaults
  gmail_extension_url: ''
  gcalendar_extension_url: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
