test:
  client_id: 34zj7xbzdn3mqvku2n8y9bcm
  client_secret: rARxqH5abJsXYT5kEHapTYn6cnz7pPdDXedNrUWwJgkPVbT7QZ
development:
  client_id: 34zj7xbzdn3mqvku2n8y9bcm
  client_secret: rARxqH5abJsXYT5kEHapTYn6cnz7pPdDXedNrUWwJgkPVbT7QZ
staging:
  client_id: 34zj7xbzdn3mqvku2n8y9bcm
  client_secret: rARxqH5abJsXYT5kEHapTYn6cnz7pPdDXedNrUWwJgkPVbT7QZ
