test:
  client_id: x9suupmx2sttrba49ncz6642
  client_secret: yG7tvQCzDJCJnnbXg3fhRzU23fWpe46Hux8fbFjMSdjjKeVACx
development:
  client_id: x9suupmx2sttrba49ncz6642
  client_secret: yG7tvQCzDJCJnnbXg3fhRzU23fWpe46Hux8fbFjMSdjjKeVACx
staging:
  client_id: x9suupmx2sttrba49ncz6642
  client_secret: yG7tvQCzDJCJnnbXg3fhRzU23fWpe46Hux8fbFjMSdjjKeVACx
