class RemoveAutoGeneratedFromProducts < ActiveRecord::Migration
  def change
    remove_column :products, :auto_generated
  end

  def down
    add_column :products, :auto_generated, :boolean
  end
end
